<a href="https://colab.research.google.com/github/doney25/CaseStudy/blob/main/pandas_casestudy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

data=pd.read_csv('https://raw.githubusercontent.com/laxmimerit/All-CSV-ML-Data-Files-Download/master/IMDB-Movie-Data.csv')
data

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [2]:
data.shape

(1000, 12)

In [3]:
data.columns

Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

In [4]:
data.head(10)

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
5,6,The Great Wall,"Action,Adventure,Fantasy",European mercenaries searching for black powde...,Yimou Zhang,"Matt Damon, Tian Jing, Willem Dafoe, Andy Lau",2016,103,6.1,56036,45.13,42.0
6,7,La La Land,"Comedy,Drama,Music",A jazz pianist falls for an aspiring actress i...,Damien Chazelle,"Ryan Gosling, Emma Stone, Rosemarie DeWitt, J....",2016,128,8.3,258682,151.06,93.0
7,8,Mindhorn,Comedy,A has-been actor best known for playing the ti...,Sean Foley,"Essie Davis, Andrea Riseborough, Julian Barrat...",2016,89,6.4,2490,NaN,71.0
8,9,The Lost City of Z,"Action,Adventure,Biography","A true-life drama, centering on British explor...",James Gray,"Charlie Hunnam, Robert Pattinson, Sienna Mille...",2016,141,7.1,7188,8.01,78.0
9,10,Passengers,"Adventure,Drama,Romance",A spacecraft traveling to a distant colony pla...,Morten Tyldum,"Jennifer Lawrence, Chris Pratt, Michael Sheen,...",2016,116,7.0,192177,100.01,41.0

In [5]:
data.dtypes

Rank                    int64
Title                  object
Genre                  object
Description            object
Director               object
Actors                 object
Year                    int64
Runtime (Minutes)       int64
Rating                float64
Votes                   int64
Revenue (Millions)    float64
Metascore             float64
dtype: object

In [6]:
data.isnull().sum()

Rank                    0
Title                   0
Genre                   0
Description             0
Director                0
Actors                  0
Year                    0
Runtime (Minutes)       0
Rating                  0
Votes                   0
Revenue (Millions)    128
Metascore              64
dtype: int64

In [7]:
print(f'Number of duplicate rows: {data.duplicated().sum()}')
data.drop_duplicates(inplace=True)

Number of duplicate rows: 0

In [8]:
data.rename(columns={'Title': 'Movie_Title'}, inplace=True)
data.columns

Index(['Rank', 'Movie_Title', 'Genre', 'Description', 'Director', 'Actors',
       'Year', 'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

In [9]:
unique_genres = data['Genre'].str.split(',').explode().unique()
print(f'Total number of unique genres: {len(unique_genres)}')
print('Unique genres:', unique_genres)

Total number of unique genres: 20
Unique genres: ['Action' 'Adventure' 'Sci-Fi' 'Mystery' 'Horror' 'Thriller' 'Animation'
 'Comedy' 'Family' 'Fantasy' 'Drama' 'Music' 'Biography' 'Romance'
 'History' 'Crime' 'Western' 'War' 'Musical' 'Sport']

In [10]:
data['Number_of_Genres'] = data['Genre'].apply(lambda x: len(str(x).split(',')))
print(data[['Movie_Title', 'Genre', 'Number_of_Genres']].head())

               Movie_Title                     Genre  Number_of_Genres
0  Guardians of the Galaxy   Action,Adventure,Sci-Fi                 3
1               Prometheus  Adventure,Mystery,Sci-Fi                 3
2                    Split           Horror,Thriller                 2
3                     Sing   Animation,Comedy,Family                 3
4            Suicide Squad  Action,Adventure,Fantasy                 3

In [11]:
data['Revenue (Millions)'].fillna(data['Revenue (Millions)'].median(), inplace=True)

data['Metascore'].fillna(data['Metascore'].median(), inplace=True)

print(data.isnull().sum())

Rank                  0
Movie_Title           0
Genre                 0
Description           0
Director              0
Actors                0
Year                  0
Runtime (Minutes)     0
Rating                0
Votes                 0
Revenue (Millions)    0
Metascore             0
Number_of_Genres      0
dtype: int64

/tmp/ipykernel_1419/3605895215.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Revenue (Millions)'].fillna(data['Revenue (Millions)'].median(), inplace=True)
/tmp/ipykernel_1419/3605895215.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Metascore'].fillna(data['Metascore'].median(), inplace=True)

In [12]:
top_5_movies_by_rating = data.sort_values(by='Rating', ascending=False).head(5)
print('Top 5 movies by Rating:')
print(top_5_movies_by_rating[['Movie_Title', 'Rating']])

Top 5 movies by Rating:
          Movie_Title  Rating
54    The Dark Knight     9.0
80          Inception     8.8
117            Dangal     8.8
36       Interstellar     8.6
249  The Intouchables     8.6

In [13]:
highest_revenue_movie = data.loc[data['Revenue (Millions)'].idxmax()]
lowest_revenue_movie = data.loc[data['Revenue (Millions)'].idxmin()]

print('Movie with Highest Revenue:')
print(highest_revenue_movie[['Movie_Title', 'Revenue (Millions)']])

print('\nMovie with Lowest Revenue:')
print(lowest_revenue_movie[['Movie_Title', 'Revenue (Millions)']])

Movie with Highest Revenue:
Movie_Title           Star Wars: Episode VII - The Force Awakens
Revenue (Millions)                                        936.63
Name: 50, dtype: object

Movie with Lowest Revenue:
Movie_Title           A Kind of Murder
Revenue (Millions)                 0.0
Name: 231, dtype: object

In [14]:
avg_rating_by_director = data.groupby('Director')['Rating'].mean().sort_values(ascending=False)
print('Average Rating by Director (Top 10):')
print(avg_rating_by_director.head(10))

Average Rating by Director (Top 10):
Director
Nitesh Tiwari                       8.80
Christopher Nolan                   8.68
Olivier Nakache                     8.60
Makoto Shinkai                      8.60
Florian Henckel von Donnersmarck    8.50
Aamir Khan                          8.50
Naoko Yamada                        8.40
Damien Chazelle                     8.40
S.S. Rajamouli                      8.30
Thomas Vinterberg                   8.30
Name: Rating, dtype: float64

In [15]:
movies_per_year = data['Year'].value_counts().sort_index()
print('Number of Movies per Year:')
print(movies_per_year)

Number of Movies per Year:
Year
2006     44
2007     53
2008     52
2009     51
2010     60
2011     63
2012     64
2013     91
2014     98
2015    127
2016    297
Name: count, dtype: int64

In [16]:
high_rating_high_revenue_movies = data[(data['Rating'] > 8) & (data['Revenue (Millions)'] > 100)]
print('Movies with Rating > 8 and Revenue > 100M:')
print(high_rating_high_revenue_movies[['Movie_Title', 'Rating', 'Revenue (Millions)']])

Movies with Rating > 8 and Revenue > 100M:
                                      Movie_Title  Rating  Revenue (Millions)
0                         Guardians of the Galaxy     8.1              333.13
6                                      La La Land     8.3              151.06
36                                   Interstellar     8.6              187.99
50     Star Wars: Episode VII - The Force Awakens     8.1              936.63
54                                The Dark Knight     9.0              533.32
67                             Mad Max: Fury Road     8.1              153.63
74                                       Zootopia     8.1              341.26
76                                   The Avengers     8.1              623.28
77                           Inglourious Basterds     8.3              120.52
80                                      Inception     8.8              292.57
82                        The Wolf of Wall Street     8.2              116.87
83                                      Gone Girl     8.1              167.74
92                                       The Help     8.1              169.71
99                                   The Departed     8.5              132.37
114  Harry Potter and the Deathly Hallows: Part 2     8.1              380.96
124                         The Dark Knight Rises     8.5              448.13
138                                Shutter Island     8.1              127.97
144                              Django Unchained     8.4              162.80
241                                    Inside Out     8.2              356.45
427                          The Bourne Ultimatum     8.1              227.14
499                                            Up     8.3              292.98
634                                        WALL·E     8.4              223.81
645                                   Gran Torino     8.2              148.09
688                                   Toy Story 3     8.3              414.98
772                      How to Train Your Dragon     8.1              217.39

In [17]:
director_stats = data.groupby('Director').agg({'Rating': 'mean', 'Revenue (Millions)': 'mean'})
print('Average Rating and Revenue by Director:')
print(director_stats.sort_values(by='Rating', ascending=False).head())

Average Rating and Revenue by Director:
                                  Rating  Revenue (Millions)
Director
Nitesh Tiwari                       8.80              11.150
Christopher Nolan                   8.68             303.018
Olivier Nakache                     8.60              13.180
Makoto Shinkai                      8.60               4.680
Florian Henckel von Donnersmarck    8.50              11.280

In [18]:
year_stats = data.groupby('Year').agg(Count=('Movie_Title', 'count'), Average_Rating=('Rating', 'mean'))
print('Number of Movies and Average Rating by Year:')
print(year_stats)

Number of Movies and Average Rating by Year:
      Count  Average_Rating
Year
2006     44        7.125000
2007     53        7.133962
2008     52        6.784615
2009     51        6.960784
2010     60        6.826667
2011     63        6.838095
2012     64        6.925000
2013     91        6.812088
2014     98        6.837755
2015    127        6.602362
2016    297        6.436700

In [19]:
data['Profitability'] = data['Revenue (Millions)'] / data['Runtime (Minutes)']
most_profitable_movies = data.sort_values(by='Profitability', ascending=False).head(10)
print('Top 10 Most Profitable Movies (Revenue per Minute):')
print(most_profitable_movies[['Movie_Title', 'Revenue (Millions)', 'Runtime (Minutes)', 'Profitability']])

Top 10 Most Profitable Movies (Revenue per Minute):
                                    Movie_Title  Revenue (Millions)  \
50   Star Wars: Episode VII - The Force Awakens              936.63
85                               Jurassic World              652.18
119                                Finding Dory              486.29
87                                       Avatar              760.51
76                                 The Avengers              623.28
15                      The Secret Life of Pets              368.31
688                                 Toy Story 3              414.98
12                                    Rogue One              532.17
174                                      Frozen              400.74
797                             Despicable Me 2              368.05

     Runtime (Minutes)  Profitability
50                 136       6.886985
85                 124       5.259516
119                 97       5.013299
87                 162       4.694506
76                 143       4.358601
15                  87       4.233448
688                103       4.028932
12                 133       4.001278
174                102       3.928824
797                 98       3.755612

In [22]:
data['Rating_Category'] = data['Rating'].apply(
    lambda x: 'Poor' if x < 5.9
    else ('Average' if x < 6.9
          else ('Good' if x < 7.9 else 'Excellent'))
)

print('Distribution of movies by Rating Category:')
print(data['Rating_Category'].value_counts())

Distribution of movies by Rating Category:
Rating_Category
Good         375
Average      359
Poor         165
Excellent    101
Name: count, dtype: int64

In [27]:
def custom_movie_score(row):
  High_score = row['Rating'] * 10 + row['Revenue (Millions)']
  return High_score

data['Movie_Score'] = data.apply(custom_movie_score, axis=1)
print('Top 10 Movies by Custom Score:')
print(data.sort_values(by='Movie_Score', ascending=False).head(10)[['Movie_Title', 'Rating', 'Revenue (Millions)', 'Metascore', 'Movie_Score']])

Top 10 Movies by Custom Score:
                                    Movie_Title  Rating  Revenue (Millions)  \
50   Star Wars: Episode VII - The Force Awakens     8.1              936.63
87                                       Avatar     7.8              760.51
85                               Jurassic World     7.0              652.18
76                                 The Avengers     8.1              623.28
54                              The Dark Knight     9.0              533.32
12                                    Rogue One     7.9              532.17
119                                Finding Dory     7.4              486.29
124                       The Dark Knight Rises     8.5              448.13
94                      Avengers: Age of Ultron     7.4              458.99
578             The Hunger Games: Catching Fire     7.6              424.65

     Metascore  Movie_Score
50        81.0      1017.63
87        83.0       838.51
85        59.0       722.18
76        69.0       704.28
54        82.0       623.32
12        65.0       611.17
119       77.0       560.29
124       78.0       533.13
94        66.0       532.99
578       76.0       500.65